const ActionTypes = {
   CONFERM_RESULT:"CONFERM_RESULT",
   GROUP_LIST:"GROUP_LIST",
   CURRENT_USER:"CURRENT_USER",
   REQUEST_LIST:"REQUEST_LIST",
   VIEW_GROUP:"VIEW_GROUP",
   MESSAGE_LIST:"MESSAGE_LIST",
   ALL_MESSAGE:"ALL_MESSAGE",
   VIEW_MESSEGE:"VIEW_MESSEGE",
   GET_MEMBER:"GET_MEMBER"
}

export default ActionTypes